# Generated by Django 5.2.12 on 2026-04-06 20:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_onboarding', models.BooleanField(default=True, verbose_name='Email — Onboarding')),
                ('email_courses', models.BooleanField(default=True, verbose_name='Email — Cours')),
                ('email_quizzes', models.BooleanField(default=True, verbose_name='Email — Quiz')),
                ('email_competences', models.BooleanField(default=True, verbose_name='Email — Compétences')),
                ('email_reminders', models.BooleanField(default=True, verbose_name='Email — Rappels')),
                ('inapp_all', models.BooleanField(default=True, verbose_name='Notifications in-app activées')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférences de notification',
                'verbose_name_plural': 'Préférences de notifications',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('ONBOARDING_ASSIGNED', "Parcours d'onboarding assigné"), ('ONBOARDING_COMPLETED', 'Onboarding complété'), ('COURSE_ENROLLED', 'Inscription à un cours'), ('COURSE_COMPLETED', 'Cours terminé'), ('QUIZ_PASSED', 'Quiz réussi'), ('QUIZ_FAILED', 'Quiz échoué'), ('COMPETENCE_VALIDATED', 'Compétence validée'), ('DUE_DATE_REMINDER', 'Rappel de date limite'), ('VALIDATION_REQUESTED', 'Validation de projet demandée'), ('VALIDATION_APPROVED', 'Validation de projet approuvée'), ('VALIDATION_REJECTED', 'Validation de projet refusée'), ('SYSTEM', 'Message système')], max_length=30, verbose_name='Type')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('action_url', models.CharField(blank=True, help_text='Ex: /formation/courses/uuid', max_length=500, verbose_name="URL d'action (frontend)")),
                ('is_read', models.BooleanField(default=False, verbose_name='Lue')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_f39341_idx')],
            },
        ),
    ]
