# Generated by Django 5.2.12 on 2026-04-06 19:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0001_initial'),
        ('formation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#01696f', max_length=7, verbose_name='Couleur hex')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie de compétence',
                'verbose_name_plural': 'Catégories de compétences',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('description', models.TextField(blank=True)),
                ('level_required', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Niveau requis (1-5)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_courses', models.ManyToManyField(blank=True, related_name='competences', to='formation.course', verbose_name='Cours liés')),
                ('related_quizzes', models.ManyToManyField(blank=True, related_name='competences', to='evaluations.quiz', verbose_name='Quiz liés')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='competences.competencecategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompetenceMatrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la matrice')),
                ('description', models.TextField(blank=True)),
                ('target_role', models.CharField(blank=True, help_text='Ex : Consultant Odoo Junior, Chef de Projet Odoo', max_length=100, verbose_name='Rôle cible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_matrices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Matrice de compétences',
                'verbose_name_plural': 'Matrices de compétences',
            },
        ),
        migrations.CreateModel(
            name='MatrixCompetenceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_level', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Niveau cible')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competences.competence')),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competences.competencematrix')),
            ],
            options={
                'verbose_name': 'Entrée matrice',
                'unique_together': {('matrix', 'competence')},
            },
        ),
        migrations.AddField(
            model_name='competencematrix',
            name='competences',
            field=models.ManyToManyField(related_name='matrices', through='competences.MatrixCompetenceEntry', to='competences.competence', verbose_name='Compétences'),
        ),
        migrations.CreateModel(
            name='CompetenceAcquisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Niveau acquis (0-5)')),
                ('source', models.CharField(choices=[('QUIZ', 'Résultat de quiz'), ('MANUAL', 'Validation manuelle'), ('COURSE_COMPLETION', 'Fin de cours')], default='MANUAL', max_length=20, verbose_name="Source d'acquisition")),
                ('notes', models.TextField(blank=True, verbose_name='Commentaires')),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquisitions', to='competences.competence', verbose_name='Compétence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competence_acquisitions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_competences', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Acquisition de compétence',
                'verbose_name_plural': 'Acquisitions de compétences',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'competence')},
            },
        ),
    ]
