# Generated by Django 5.2.12 on 2026-04-06 19:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('first_name', models.CharField(max_length=150, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=150, verbose_name='Nom')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('HR', 'RH'), ('MANAGER', 'Manager'), ('TRAINER', 'Formateur'), ('ODOO_REF', 'Référent Odoo'), ('LEARNER', 'Apprenant')], default='LEARNER', max_length=20, verbose_name='Rôle')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Département / équipe')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff admin')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='Biographie')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de prise de poste')),
                ('contract_type', models.CharField(blank=True, help_text='Ex : CDI, CDD, Stage, Alternance', max_length=50, verbose_name='Type de contrat')),
                ('project_status', models.CharField(choices=[('ONBOARDING', 'En onboarding'), ('TRAINING', 'En formation'), ('EVALUATION', 'En évaluation'), ('CONSOLIDATION', 'En consolidation'), ('VALIDATED', 'Validé pour projet'), ('NOT_READY', 'Non encore prêt')], default='ONBOARDING', max_length=30, verbose_name='Statut projet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
    ]
