# Generated by Django 5.2.12 on 2026-04-06 19:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('step_type', models.CharField(choices=[('DOCUMENT_READ', 'Lecture de document'), ('TASK_COMPLETE', 'Tâche à compléter'), ('VIDEO_WATCH', 'Vidéo à regarder'), ('FORM_FILL', 'Formulaire à remplir')], default='TASK_COMPLETE', max_length=20, verbose_name="Type d'étape")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Obligatoire')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée estimée (minutes)')),
                ('content_url', models.URLField(blank=True, verbose_name='Lien vers le contenu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Étape d'onboarding",
                'verbose_name_plural': "Étapes d'onboarding",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titre du document')),
                ('file', models.FileField(upload_to='onboarding/documents/', verbose_name='Fichier')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='onboarding.onboardingstep', verbose_name='Étape')),
            ],
            options={
                'verbose_name': "Document d'onboarding",
                'verbose_name_plural': "Documents d'onboarding",
            },
        ),
        migrations.CreateModel(
            name='OnboardingTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': "Template d'onboarding",
                'verbose_name_plural': "Templates d'onboarding",
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='onboardingstep',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='onboarding.onboardingtemplate', verbose_name='Template'),
        ),
        migrations.CreateModel(
            name='OnboardingAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Date limite')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_onboardings', to=settings.AUTH_USER_MODEL, verbose_name='Assigné par')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Apprenant')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='onboarding.onboardingtemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': "Assignment d'onboarding",
                'verbose_name_plural': "Assignments d'onboarding",
                'unique_together': {('user', 'template')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='onboardingstep',
            unique_together={('template', 'order')},
        ),
        migrations.CreateModel(
            name='StepCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, verbose_name='Note / commentaire')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='onboarding.onboardingassignment', verbose_name='Assignment')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='onboarding.onboardingstep', verbose_name='Étape')),
            ],
            options={
                'verbose_name': "Complétion d'étape",
                'verbose_name_plural': "Complétions d'étapes",
                'unique_together': {('assignment', 'step')},
            },
        ),
    ]
